baseURL = "https://example.org/"
languageCode = "zh-CN"
title = "亚博体育"
theme = "default"
publishDir = "docs"
disableHugoGeneratorInject = true

[permalinks]
  posts = "/:filename/"

[params]
  description = "亚博体育APP，覆盖全球体育赛事。亚洲最大的在体育娱乐公司，提供全套体育娱乐产品的一站式服务网站。"